### ISSUE TITLE
Installation issue on FreeBSD 11.1

### ISSUE THREAD

**Issue by peter-thoenen** [sindresorhus/pure#341]
### General information

- Pure version: 1.5.2
- ZSH version: 5.4.1
- Terminal program & version: vt100 (OpenSSH default 7.2p2)
- Operating system: FreeBSD 11.1
- ZSH framework: None

I have:
Followed install directions, failed

### Problem description

PREFACE: Yes I'm running this as root, no I don't sudo installed nor any plan to.  Yes I looked at issue #176 

Error logs follow:

```
-------- OUTPUT LOG ---------

prh-i-dark# npm  install --global pure-prompt

\> pure-prompt@1.5.2 postinstall /usr/local/lib/node_modules/pure-prompt
\> PURE_DEST=/usr/local/share/zsh/site-functions npm run --silent postinstall-link && exit 0; PURE_DEST="$PWD/functions" npm run postinstall-link && npm run postinstall-fail-instructions

ln: /usr/local/share/zsh/site-functions/prompt_pure_setup: Permission denied

â”Œâ”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”
â”‚              npm update check failed              â”‚
â”‚        Try running with sudo or get access        â”‚
â”‚       to the local update config store via        â”‚
â”‚ sudo chown -R $USER:$(id -gn $USER) /root/.config â”‚
â””â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”˜

\> pure-prompt@1.5.2 postinstall-link /usr/local/lib/node_modules/pure-prompt
\> mkdir -p "$PURE_DEST" && ln -sf "$PWD/pure.zsh" "$PURE_DEST/prompt_pure_setup" && ln -sf "$PWD/async.zsh" "$PURE_DEST/async"

mkdir: /usr/local/lib/node_modules/pure-prompt/functions: Permission denied
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pure-prompt@1.5.2 postinstall-link: `mkdir -p "$PURE_DEST" && ln -sf "$PWD/pure.zsh" "$PURE_DEST/prompt_pure_setup" && ln -sf "$PWD/async.zsh" "$PURE_DEST/async"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pure-prompt@1.5.2 postinstall-link script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

â”Œâ”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”
â”‚              npm update check failed              â”‚
â”‚        Try running with sudo or get access        â”‚
â”‚       to the local update config store via        â”‚
â”‚ sudo chown -R $USER:$(id -gn $USER) /root/.config â”‚
â””â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”˜
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pure-prompt@1.5.2 postinstall: `PURE_DEST=/usr/local/share/zsh/site-functions npm run --silent postinstall-link && exit 0; PURE_DEST="$PWD/functions" npm run postinstall-link && npm run postinstall-fail-instructions`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pure-prompt@1.5.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-08-15T01_01_30_731Z-debug.log

--------------- NPM LOG ABOVE ----------------------

prh-i-dark# cat /root/.npm/_logs/2017-08-15T01_01_30_731Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--global',
1 verbose cli   'pure-prompt' ]
2 info using npm@5.3.0
3 info using node@v8.3.0
4 verbose npm-session 442b8264839cdb2a
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 304 https://registry.npmjs.org/pure-prompt 872ms (from cache)
8 silly pacote tag manifest for pure-prompt@latest fetched in 910ms
9 silly install loadIdealTree
10 silly install cloneCurrentTreeToIdealTree
11 silly install loadShrinkwrap
12 silly install loadAllDepsIntoIdealTree
13 silly resolveWithNewModule pure-prompt@1.5.2 checking installable status
14 silly currentTree lib
15 silly idealTree lib
15 silly idealTree `-- pure-prompt@1.5.2
16 silly install generateActionsToTake
17 silly diffTrees action count 1
18 silly diffTrees add pure-prompt@1.5.2
19 silly decomposeActions action count 8
20 silly decomposeActions fetch pure-prompt@1.5.2
21 silly decomposeActions extract pure-prompt@1.5.2
22 silly decomposeActions preinstall pure-prompt@1.5.2
23 silly decomposeActions build pure-prompt@1.5.2
24 silly decomposeActions install pure-prompt@1.5.2
25 silly decomposeActions postinstall pure-prompt@1.5.2
26 silly decomposeActions finalize pure-prompt@1.5.2
27 silly decomposeActions refresh-package-json pure-prompt@1.5.2
28 silly install executeActions
29 silly doSerial global-install 8
30 verbose correctMkdir /root/.npm/_locks correctMkdir not in flight; initializing
31 verbose lock using /root/.npm/_locks/staging-3a08f0df5026584d.lock for /usr/local/lib/node_modules/.staging
32 silly doParallel extract 8
33 silly extract pure-prompt@1.5.2
34 silly doReverseSerial unbuild 8
35 silly doSerial remove 8
36 silly doSerial move 8
37 silly doSerial finalize 8
38 silly finalize /usr/local/lib/node_modules/pure-prompt
39 silly doParallel refresh-package-json 8
40 silly refresh-package-json /usr/local/lib/node_modules/pure-prompt
41 silly doParallel preinstall 8
42 silly preinstall pure-prompt@1.5.2
43 info lifecycle pure-prompt@1.5.2~preinstall: pure-prompt@1.5.2
44 silly doSerial build 8
45 silly build pure-prompt@1.5.2
46 info linkStuff pure-prompt@1.5.2
47 silly linkStuff pure-prompt@1.5.2 has /usr/local/lib/node_modules as its parent node_modules
48 silly linkStuff pure-prompt@1.5.2 is part of a global install
49 silly linkStuff pure-prompt@1.5.2 is installed into a global node_modules
50 silly linkStuff pure-prompt@1.5.2 is installed into the top-level global node_modules
51 verbose linkBins pure-prompt@1.5.2
52 verbose linkMans pure-prompt@1.5.2
53 silly doSerial global-link 8
54 silly doParallel update-linked 8
55 silly doSerial install 8
56 silly install pure-prompt@1.5.2
57 info lifecycle pure-prompt@1.5.2~install: pure-prompt@1.5.2
58 silly doSerial postinstall 8
59 silly postinstall pure-prompt@1.5.2
60 info lifecycle pure-prompt@1.5.2~postinstall: pure-prompt@1.5.2
61 verbose lifecycle pure-prompt@1.5.2~postinstall: unsafe-perm in lifecycle false
62 verbose lifecycle pure-prompt@1.5.2~postinstall: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/usr/local/lib/node_modules/pure-prompt/node_modules/.bin:/usr/local/lib/node_modules/.bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:/root/bin
63 verbose lifecycle pure-prompt@1.5.2~postinstall: CWD: /usr/local/lib/node_modules/pure-prompt
64 silly lifecycle pure-prompt@1.5.2~postinstall: Args: [ '-c',
64 silly lifecycle   'PURE_DEST=/usr/local/share/zsh/site-functions npm run --silent postinstall-link && exit 0; PURE_DEST="$PWD/functions" npm run postinstall-link && npm run postinstall-fail-instructions' ]
65 silly lifecycle pure-prompt@1.5.2~postinstall: Returned: code: 1  signal: null
66 info lifecycle pure-prompt@1.5.2~postinstall: Failed to exec postinstall script
67 verbose unlock done using /root/.npm/_locks/staging-3a08f0df5026584d.lock for /usr/local/lib/node_modules/.staging
68 verbose stack Error: pure-prompt@1.5.2 postinstall: `PURE_DEST=/usr/local/share/zsh/site-functions npm run --silent postinstall-link && exit 0; PURE_DEST="$PWD/functions" npm run postinstall-link && npm run postinstall-fail-instructions`
68 verbose stack Exit status 1
68 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:289:16)
68 verbose stack     at emitTwo (events.js:125:13)
68 verbose stack     at EventEmitter.emit (events.js:213:7)
68 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
68 verbose stack     at emitTwo (events.js:125:13)
68 verbose stack     at ChildProcess.emit (events.js:213:7)
68 verbose stack     at maybeClose (internal/child_process.js:927:16)
68 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
69 verbose pkgid pure-prompt@1.5.2
70 verbose cwd /root
71 verbose FreeBSD 11.1-RELEASE
72 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--global" "pure-prompt"
73 verbose node v8.3.0
74 verbose npm  v5.3.0
75 error code ELIFECYCLE
76 error errno 1
77 error pure-prompt@1.5.2 postinstall: `PURE_DEST=/usr/local/share/zsh/site-functions npm run --silent postinstall-link && exit 0; PURE_DEST="$PWD/functions" npm run postinstall-link && npm run postinstall-fail-instructions`
77 error Exit status 1
78 error Failed at the pure-prompt@1.5.2 postinstall script.
78 error This is probably not a problem with npm. There is likely additional logging output above.
79 verbose exit [ 1, true ]
```

### Reproduction steps

1. Attempt to install with npm

### My `.zshrc`:

None, completely empty

**Comment by mafredri** [comment]
To be honest I don't even know where to start, this seems like more of a problem with `npm` than Pure. Have you tried updating `node` and `npm` to their latest versions?

Even the *fallback* isn't working (`mkdir /usr/local/lib/node_modules/pure-prompt/functions`) which makes no sense. Since you are root this indicates to me that your filesystem has messed up permissions or is read-only.

**Comment by kruttschu** [comment]
i had the same problem with node 6  from https://nodejs.org/en/download/package-manager/#enterprise-linux-and-fedora on centos 7
but it worked with
~ root@CentOS-73-64-minimal
❯ npm -v
5.3.0

~ root@CentOS-73-64-minimal
❯ node -v
v8.4.0

@mafredri refering to #176:  I think it is a very valid case to install a prompt for root as root.

do you use any kind of package manager like apt, yum, dnf, pacman,...

people give you trust by installing your software, and other people due to the opensource nature of your project review your work. I think there should be some trust in the good people who make software for other people.

as sudo says(excerpt):

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

if you would do such thing, as deleting all my/our files, you would never be trusted by someone again.

Probably your right, and you are not worth trusting.
and there should only be a state controlled repository, where all software is controlled and hosted.. oh wait, no good idea, because the state is also spying on us.

⚘⚘⚘⚘⚘⚘⚘⚘⚘⚘⚘⚘⚘⚘⚘⚘⚘⚘⚘⚘⚘⚘⚘⚘⚘⚘⚘⚘⚘⚘⚘⚘⚘⚘⚘⚘⚘⚘⚘⚘⚘⚘⚘⚘⚘⚘⚘⚘⚘⚘⚘
⚘best is we all go out gardening, and leave the idea behind us, that a opensource community works ⚘
⚘by trusting that others would do as any good.                                                                                      ⚘
⚘⚘⚘⚘⚘⚘⚘⚘⚘⚘⚘⚘⚘⚘⚘⚘⚘⚘⚘⚘⚘⚘⚘⚘⚘⚘⚘⚘⚘⚘⚘⚘⚘⚘⚘⚘⚘⚘⚘⚘⚘⚘⚘⚘⚘⚘⚘⚘⚘⚘⚘

anyway thanx for your work, i installed as root, so consider yourself trusted by me :)

**Comment by kruttschu** [comment]
also with user permission, you could alter my PATH=~.evil:$PATH and add a script called sudo in .evil,
#!/bin/bash
/usr/bin/sudo rm -rf /  #or better download reverseshell, rootkit or something

**Comment by oldskool** [comment]
I'm having the same issue on Ubuntu 16.04 with npm 5.3.0.

```
root@app1-prod:~# npm install -g pure-prompt   

> pure-prompt@1.5.2 postinstall /usr/lib/node_modules/pure-prompt
> PURE_DEST=/usr/local/share/zsh/site-functions npm run --silent postinstall-link && exit 0; PURE_DEST="$PWD/functions" npm run postinstall-link && npm run postinstall-fail-instructions

glob error { Error: EACCES: permission denied, scandir '/root/.npm/_logs'
    at Error (native)
  stack: 'Error: EACCES: permission denied, scandir \'/root/.npm/_logs\'\n    at Error (native)',
  errno: -13,
  code: 'EACCES',
  syscall: 'scandir',
  path: '/root/.npm/_logs' }

┌───────────────────────────────────────────────────┐
│              npm update check failed              │
│        Try running with sudo or get access        │
│       to the local update config store via        │
│ sudo chown -R $USER:$(id -gn $USER) /root/.config │
└───────────────────────────────────────────────────┘
npm ERR! path /root/.npm/_logs
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall scandir
npm ERR! Error: EACCES: permission denied, scandir '/root/.npm/_logs'
npm ERR!     at Error (native)
npm ERR!  { Error: EACCES: permission denied, scandir '/root/.npm/_logs'
npm ERR!     at Error (native)
npm ERR!   stack: 'Error: EACCES: permission denied, scandir \'/root/.npm/_logs\'\n    at Error (native)',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'scandir',
npm ERR!   path: '/root/.npm/_logs' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.
glob error { Error: EACCES: permission denied, scandir '/root/.npm/_logs'
    at Error (native)
  stack: 'Error: EACCES: permission denied, scandir \'/root/.npm/_logs\'\n    at Error (native)',
  errno: -13,
  code: 'EACCES',
  syscall: 'scandir',
  path: '/root/.npm/_logs' }

> pure-prompt@1.5.2 postinstall-link /usr/lib/node_modules/pure-prompt
> mkdir -p "$PURE_DEST" && ln -sf "$PWD/pure.zsh" "$PURE_DEST/prompt_pure_setup" && ln -sf "$PWD/async.zsh" "$PURE_DEST/async"

mkdir: cannot create directory ‘/usr/lib/node_modules/pure-prompt/functions’: Permission denied
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pure-prompt@1.5.2 postinstall-link: `mkdir -p "$PURE_DEST" && ln -sf "$PWD/pure.zsh" "$PURE_DEST/prompt_pure_setup" && ln -sf "$PWD/async.zsh" "$PURE_DEST/async"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pure-prompt@1.5.2 postinstall-link script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

┌───────────────────────────────────────────────────┐
│              npm update check failed              │
│        Try running with sudo or get access        │
│       to the local update config store via        │
│ sudo chown -R $USER:$(id -gn $USER) /root/.config │
└───────────────────────────────────────────────────┘
npm ERR! code ELIFECYCLE
npm ERR! errno 243
npm ERR! pure-prompt@1.5.2 postinstall: `PURE_DEST=/usr/local/share/zsh/site-functions npm run --silent postinstall-link && exit 0; PURE_DEST="$PWD/functions" npm run postinstall-link && npm run postinstall-fail-instructions`
npm ERR! Exit status 243
npm ERR! 
npm ERR! Failed at the pure-prompt@1.5.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-08-30T12_24_52_966Z-debug.log
```

The mentioned log file looks like this:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'pure-prompt' ]
2 info using npm@5.3.0
3 info using node@v6.11.2
4 verbose npm-session 29c466e6b96316dc
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 200 https://registry.npmjs.org/pure-prompt 20ms (from cache)
8 silly pacote tag manifest for pure-prompt@latest fetched in 47ms
9 silly install loadIdealTree
10 silly install cloneCurrentTreeToIdealTree
11 silly install loadShrinkwrap
12 silly install loadAllDepsIntoIdealTree
13 silly resolveWithNewModule pure-prompt@1.5.2 checking installable status
14 silly currentTree lib
15 silly idealTree lib
15 silly idealTree └── pure-prompt@1.5.2
16 silly install generateActionsToTake
17 silly diffTrees action count 1
18 silly diffTrees add pure-prompt@1.5.2
19 silly decomposeActions action count 8
20 silly decomposeActions fetch pure-prompt@1.5.2
21 silly decomposeActions extract pure-prompt@1.5.2
22 silly decomposeActions preinstall pure-prompt@1.5.2
23 silly decomposeActions build pure-prompt@1.5.2
24 silly decomposeActions install pure-prompt@1.5.2
25 silly decomposeActions postinstall pure-prompt@1.5.2
26 silly decomposeActions finalize pure-prompt@1.5.2
27 silly decomposeActions refresh-package-json pure-prompt@1.5.2
28 silly install executeActions
29 silly doSerial global-install 8
30 verbose correctMkdir /root/.npm/_locks correctMkdir not in flight; initializing
31 verbose lock using /root/.npm/_locks/staging-a072192f34a17023.lock for /usr/lib/node_modules/.staging
32 silly doParallel extract 8
33 silly extract pure-prompt@1.5.2
34 silly doReverseSerial unbuild 8
35 silly doSerial remove 8
36 silly doSerial move 8
37 silly doSerial finalize 8
38 silly finalize /usr/lib/node_modules/pure-prompt
39 silly doParallel refresh-package-json 8
40 silly refresh-package-json /usr/lib/node_modules/pure-prompt
41 silly doParallel preinstall 8
42 silly preinstall pure-prompt@1.5.2
43 info lifecycle pure-prompt@1.5.2~preinstall: pure-prompt@1.5.2
44 silly doSerial build 8
45 silly build pure-prompt@1.5.2
46 info linkStuff pure-prompt@1.5.2
47 silly linkStuff pure-prompt@1.5.2 has /usr/lib/node_modules as its parent node_modules
48 silly linkStuff pure-prompt@1.5.2 is part of a global install
49 silly linkStuff pure-prompt@1.5.2 is installed into a global node_modules
50 silly linkStuff pure-prompt@1.5.2 is installed into the top-level global node_modules
51 verbose linkBins pure-prompt@1.5.2
52 verbose linkMans pure-prompt@1.5.2
53 silly doSerial global-link 8
54 silly doParallel update-linked 8
55 silly doSerial install 8
56 silly install pure-prompt@1.5.2
57 info lifecycle pure-prompt@1.5.2~install: pure-prompt@1.5.2
58 silly doSerial postinstall 8
59 silly postinstall pure-prompt@1.5.2
60 info lifecycle pure-prompt@1.5.2~postinstall: pure-prompt@1.5.2
61 verbose lifecycle pure-prompt@1.5.2~postinstall: unsafe-perm in lifecycle false
62 verbose lifecycle pure-prompt@1.5.2~postinstall: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/usr/lib/node_modules/pure-prompt/node_modules/.bin:/usr/lib/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
63 verbose lifecycle pure-prompt@1.5.2~postinstall: CWD: /usr/lib/node_modules/pure-prompt
64 silly lifecycle pure-prompt@1.5.2~postinstall: Args: [ '-c',
64 silly lifecycle   'PURE_DEST=/usr/local/share/zsh/site-functions npm run --silent postinstall-link && exit 0; PURE_DEST="$PWD/functions" npm run postinstall-link && npm run postinstall-fail-instructions' ]
65 silly lifecycle pure-prompt@1.5.2~postinstall: Returned: code: 243  signal: null
66 info lifecycle pure-prompt@1.5.2~postinstall: Failed to exec postinstall script
67 verbose unlock done using /root/.npm/_locks/staging-a072192f34a17023.lock for /usr/lib/node_modules/.staging
68 verbose stack Error: pure-prompt@1.5.2 postinstall: `PURE_DEST=/usr/local/share/zsh/site-functions npm run --silent postinstall-link && exit 0; PURE_DEST="$PWD/functions" npm run postinstall-link && npm run postinstall-fail-instructions`
68 verbose stack Exit status 243
68 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:289:16)
68 verbose stack     at emitTwo (events.js:106:13)
68 verbose stack     at EventEmitter.emit (events.js:191:7)
68 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
68 verbose stack     at emitTwo (events.js:106:13)
68 verbose stack     at ChildProcess.emit (events.js:191:7)
68 verbose stack     at maybeClose (internal/child_process.js:891:16)
68 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
69 verbose pkgid pure-prompt@1.5.2
70 verbose cwd /root
71 verbose Linux 4.4.0-93-generic
72 verbose argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "pure-prompt"
73 verbose node v6.11.2
74 verbose npm  v5.3.0
75 error code ELIFECYCLE
76 error errno 243
77 error pure-prompt@1.5.2 postinstall: `PURE_DEST=/usr/local/share/zsh/site-functions npm run --silent postinstall-link && exit 0; PURE_DEST="$PWD/functions" npm run postinstall-link && npm run postinstall-fail-instructions`
77 error Exit status 243
78 error Failed at the pure-prompt@1.5.2 postinstall script.
78 error This is probably not a problem with npm. There is likely additional logging output above.
79 verbose exit [ 243, true ]
```

This is on a brand new machine, so I'm pretty sure the filesystem permissions are not problematic, nor is the filesystem in read only mode.

**Comment by oldskool** [comment]
Could the change in https://github.com/sindresorhus/pure/commit/f879cc55eb8f971e24decf87cff617cabeff65d5 have anything to do with it? When I manually tried to install version 1.5.1 it did trigger this error message. The latest version probably is trying to do the same, but maybe because of the missing fpath, it can't find/create some stuff.

**Comment by mafredri** [comment]
@oldskool that change only affects the output that is printed, so it will have no effect on the install process.

I do not believe these issues can be fixed in pure, they seem to stem from running node as root.

I found a few similar cases, see https://github.com/infinitered/ignite/issues/246 and 
https://github.com/hexojs/hexo/issues/2505#issuecomment-294123974 for potential solutions.

I'm closing this as I don't see how we can fix it in Pure.

**Comment by mafredri** [comment]
@kruttschu thanks for the report and your trust. It's not my meaning to say how you should or shouldn't use root, I simply want to warn users in case they are using sudo "just to get it to work". I provided the hypothetical scenscenario to try to illustrate the potential for harm 🙂. It was never meant for people who know what they are doing.

**Comment by nrebhun** [comment]
A workaround I threw together for a Debian 9 server, though I believe it may help the less experienced, such as myself.

I would, however, like to take this opportunity to wave the "**sudo chown is dangerous**" flag:

## ⚠️ **Make sure you know what you're doing, and what the implications of `sudo chown` are, should you type something in wrong** ⚠️ 🚩

```sh
# Take ownership of global 'node_modules':
$ sudo chown -R $USER:$(id -gn $USER) <path-to-global-node_modules-dir>
# Take ownership of your zsh's site-functions:
$ sudo chown -R $USER:$USER(id -gn $USER) <path-to-your-zsh-'site-functions'-dir>
```
And wrapped up with:
```sh
$ npm install --global pure-prompt
```
