### ISSUE TITLE
Instalation issue on Enterprise Linux 7x

### ISSUE THREAD

**Issue by fellipeh** [sindresorhus/pure#352]
### General information

- Pure version: 1.5.2
- ZSH version: 5.0.2
- Terminal program & version: Gnome Terminal and Terminator  
- Operating system: Enterprise Linux 7x 
- ZSH framework: None

I have:
- [x] Tested with another terminal program and can reproduce the issue: 
- [X] Followed the [Integration](https://github.com/sindresorhus/pure#integration) instructions for my framework

### Problem description
Erro when install on RHEL 7x

### Reproduction steps

1. install Pure in terminal
2. sudo npm install --global pure-prompt

### My `.zshrc`:
export ZSH=/home/fellipeh/.oh-my-zsh
ZSH_THEME=""
plugins=(git)
source $ZSH/oh-my-zsh.sh

### Error:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--global',
1 verbose cli   'pure-prompt' ]
2 info using npm@5.3.0
3 info using node@v8.6.0
4 verbose npm-session c17dea269e01f24a
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 200 https://registry.npmjs.org/pure-prompt 742ms
8 silly pacote tag manifest for pure-prompt@latest fetched in 771ms
9 silly install loadIdealTree
10 silly install cloneCurrentTreeToIdealTree
11 silly install loadShrinkwrap
12 silly install loadAllDepsIntoIdealTree
13 silly resolveWithNewModule pure-prompt@1.5.2 checking installable status
14 silly currentTree lib
15 silly idealTree lib
15 silly idealTree └── pure-prompt@1.5.2
16 silly install generateActionsToTake
17 silly diffTrees action count 1
18 silly diffTrees add pure-prompt@1.5.2
19 silly decomposeActions action count 8
20 silly decomposeActions fetch pure-prompt@1.5.2
21 silly decomposeActions extract pure-prompt@1.5.2
22 silly decomposeActions preinstall pure-prompt@1.5.2
23 silly decomposeActions build pure-prompt@1.5.2
24 silly decomposeActions install pure-prompt@1.5.2
25 silly decomposeActions postinstall pure-prompt@1.5.2
26 silly decomposeActions finalize pure-prompt@1.5.2
27 silly decomposeActions refresh-package-json pure-prompt@1.5.2
28 silly install executeActions
29 silly doSerial global-install 8
30 verbose correctMkdir /root/.npm/_locks correctMkdir not in flight; initializing
31 verbose makeDirectory /root/.npm/_locks creation not in flight; initializing
32 silly makeDirectory /root/.npm/_locks uid: 1000 gid: 1001
33 verbose lock using /root/.npm/_locks/staging-a072192f34a17023.lock for /usr/lib/node_modules/.staging
34 silly doParallel extract 8
35 silly extract pure-prompt@1.5.2
36 silly doReverseSerial unbuild 8
37 silly doSerial remove 8
38 silly doSerial move 8
39 silly doSerial finalize 8
40 silly finalize /usr/lib/node_modules/pure-prompt
41 silly doParallel refresh-package-json 8
42 silly refresh-package-json /usr/lib/node_modules/pure-prompt
43 silly doParallel preinstall 8
44 silly preinstall pure-prompt@1.5.2
45 info lifecycle pure-prompt@1.5.2~preinstall: pure-prompt@1.5.2
46 silly doSerial build 8
47 silly build pure-prompt@1.5.2
48 info linkStuff pure-prompt@1.5.2
49 silly linkStuff pure-prompt@1.5.2 has /usr/lib/node_modules as its parent node_modules
50 silly linkStuff pure-prompt@1.5.2 is part of a global install
51 silly linkStuff pure-prompt@1.5.2 is installed into a global node_modules
52 silly linkStuff pure-prompt@1.5.2 is installed into the top-level global node_modules
53 verbose linkBins pure-prompt@1.5.2
54 verbose linkMans pure-prompt@1.5.2
55 silly doSerial global-link 8
56 silly doParallel update-linked 8
57 silly doSerial install 8
58 silly install pure-prompt@1.5.2
59 info lifecycle pure-prompt@1.5.2~install: pure-prompt@1.5.2
60 silly doSerial postinstall 8
61 silly postinstall pure-prompt@1.5.2
62 info lifecycle pure-prompt@1.5.2~postinstall: pure-prompt@1.5.2
63 verbose lifecycle pure-prompt@1.5.2~postinstall: unsafe-perm in lifecycle false
64 verbose lifecycle pure-prompt@1.5.2~postinstall: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/usr/lib/node_modules/pure-prompt/node_modules/.bin:/usr/lib/node_modules/.bin:/sbin:/bin:/usr/sbin:/usr/bin
65 verbose lifecycle pure-prompt@1.5.2~postinstall: CWD: /usr/lib/node_modules/pure-prompt
66 silly lifecycle pure-prompt@1.5.2~postinstall: Args: [ '-c',
66 silly lifecycle   'PURE_DEST=/usr/local/share/zsh/site-functions npm run --silent postinstall-link && exit 0; PURE_DEST="$PWD/functions" npm run postinstall-link && npm run postinstall-fail-instructions' ]
67 silly lifecycle pure-prompt@1.5.2~postinstall: Returned: code: 243  signal: null
68 info lifecycle pure-prompt@1.5.2~postinstall: Failed to exec postinstall script
69 verbose unlock done using /root/.npm/_locks/staging-a072192f34a17023.lock for /usr/lib/node_modules/.staging
70 verbose stack Error: pure-prompt@1.5.2 postinstall: `PURE_DEST=/usr/local/share/zsh/site-functions npm run --silent postinstall-link && exit 0; PURE_DEST="$PWD/functions" npm run postinstall-link && npm run postinstall-fail-instructions`
70 verbose stack Exit status 243
70 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:289:16)
70 verbose stack     at emitTwo (events.js:125:13)
70 verbose stack     at EventEmitter.emit (events.js:213:7)
70 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
70 verbose stack     at emitTwo (events.js:125:13)
70 verbose stack     at ChildProcess.emit (events.js:213:7)
70 verbose stack     at maybeClose (internal/child_process.js:927:16)
70 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
71 verbose pkgid pure-prompt@1.5.2
72 verbose cwd /home/fellipeh
73 verbose Linux 3.10.0-693.2.2.el7.x86_64
74 verbose argv "/usr/bin/node" "/bin/npm" "install" "--global" "pure-prompt"
75 verbose node v8.6.0
76 verbose npm  v5.3.0
77 error code ELIFECYCLE
78 error errno 243
79 error pure-prompt@1.5.2 postinstall: `PURE_DEST=/usr/local/share/zsh/site-functions npm run --silent postinstall-link && exit 0; PURE_DEST="$PWD/functions" npm run postinstall-link && npm run postinstall-fail-instructions`
79 error Exit status 243
80 error Failed at the pure-prompt@1.5.2 postinstall script.
80 error This is probably not a problem with npm. There is likely additional logging output above.
81 verbose exit [ 243, true ]
```

**Comment by mafredri** [comment]
Can you try this:

```
sudo npm install --global pure-prompt --allow-root --unsafe-perm=true
```

as suggested by @kedwin in https://github.com/sindresorhus/pure/issues/342#issuecomment-340291581?

**Comment by mafredri** [comment]
Closed due to age.
